### ISSUE TITLE
Code is not Implementing on Android Studio

### ISSUE THREAD

**Issue by Shaquibrahman22** [arsvechkarev/TimerX#1]
The Timerx code is not getting implemented on Android Studio. It's showing this error : Failed to resolve: com.arsvechkarev:timerx:2.0.0 please provide the information regarding how to implement this dependency or is there any new version available.

**Comment by arsvechkarev** [comment]
Thanks for noticing! I've added package to jcenter, so now everything should be fine. Make sure you have jcenter() added in your top-level build.gradle file.
