### ISSUE TITLE
OnTick in 1 Second

### ISSUE THREAD

**Issue by rupeshbhade** [arsvechkarev/TimerX#2]
When i am going to use this TimerX API its executing multiple time in a tick.
Can we make this timer to 1 second tick

**Comment by arsvechkarev** [comment]
Hi rupeshbhade!
How many timer will call "onTick()" depends on how you define input format for formatting time.

For example, defining format as "MM:SS" will result in changing time every second, defining format as "SS-LLL" will be changing time every millisecond (check out wiki if you want to learn more about formats).

Tell whether that solves your problem

**Comment by rupeshbhade** [comment]
`int xTimeCount = 0;
Stopwatch stopwatch =new StopwatchBuilder()
                .startFormat("MM:SS")
                .onTick(new TimeTickListener() {
                    @Override
                    public void onTick(@NotNull CharSequence time) {
                        counter.setText(time);
                        xTimeCount++;
                        Timber.d(xTimeCount); // printing log multiple time in a second.
                })
                .actionWhen(1, TimeUnit.MINUTES, () -> startCall = true)
                .changeFormatWhen(1, TimeUnit.HOURS, "HH:MM:SS")
                .build();
        stopwatch.start();`

This code is writing log multiple time in a second.
it should write one log in a second.

**Comment by Merthan** [comment]
@arsvechkarev He is right, with Format MM:SS onTick gets called between 2-5 times per second.

Apart from that I really like the library, thanks!

**Comment by arsvechkarev** [comment]
Okay, thank you all for noticing, in a couple of days I will be releasing a new version where this issue is fixed

**Comment by Merthan** [comment]
No rush, I'll use the Timer in my Bluetooth Presenter App @arsvechkarev 

https://play.google.com/store/apps/details?id=com.me.btp
If you want a code to get it for free, tell me.
Otherwise you can also test the free one first
https://play.google.com/store/apps/details?id=com.me.btp.free

You'll see what I used the timer for in the next version, maybe coming within the next 2 weeks

**Comment by arsvechkarev** [comment]
I've just released version 3.1.0, in which there is a `useExactDelay` property of timer and stopwatch, it is specially designed to fix your problem, you can check in out. And although it is obviously too late, I hope this will be of use for somebody in the future :)
