### ISSUE TITLE
'Start from' for Stopwatch?

### ISSUE THREAD

**Issue by zhombie** [arsvechkarev/TimerX#3]
What about adding a new feature, which will give an ability to define start time for stopwatch?

**Comment by arsvechkarev** [comment]
Hi zhombie!

I think the point of stopwatch is to count how much time passed since the moment the stopwatch started. I don't think starting a stopwatch from a particular time makes a lot of sense.

Perhaps I'm wrong, so could you tell more about your use case and why do you need such a feature?

**Comment by zhombie** [comment]
Hi, thanks for response.

Sometimes after Stopwatch release you don't have an ability to restore state, you can just start from 0. I have some situations where you can't determine will Stopwatch be released & will be used after or work by default.

So i just wanted to set a start time as state restoration. It is your library, my wish is just an extra feature, which will be useful, but can hurt whole concept of Stopwatch

**Comment by AlirezaNezami96** [comment]
Yeah, I'm kind of have this issue too right now. I think I will customize it a little bit myself. But Thanks for this. Awesome work

**Comment by paricleu** [comment]
I just opened a [PR](https://github.com/arsvechkarev/TimerX/pull/6) to add a startTime method to Stopwatch.
If you want to use it before this gets merged here is the repo:

Step 1. Add it in your root build.gradle at the end of repositories:

```
allprojects {
	repositories {
		...
		maven { url 'https://jitpack.io' }
	}
}
```
Step 2. Add the dependency

```
dependencies {
	implementation 'com.github.paricleu:TimerX:develop-SNAPSHOT'
}
```

**Comment by zhombie** [comment]
Feature added:

https://github.com/arsvechkarev/TimerX/releases/tag/3.0.0
