### ISSUE TITLE
Migrate to other Maven repository

### ISSUE THREAD

**Issue by MrReSc** [arsvechkarev/TimerX#5]
Since the latest Gradle update I get the following message:

```
Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
```
I think you will have to move your plugin in the near future.
Actually, you should be able to use GitHub for this.

**Comment by MrReSc** [comment]
Basically, it already works with [jitpack.io](https://jitpack.io/).

`implementation 'com.github.arsvechkarev:TimerX:-SNAPSHOT'`

It would be better if you created a relase, then it would be clearly recognisable.

**Comment by arsvechkarev** [comment]
Hi! I created a release 3.1.0, so now everything should be working properly
